"""Storage service for downloading and uploading via presigned URLs."""

import asyncio
import logging

import httpx

from app.config import Settings, get_settings
from app.exceptions import UploadError, ValidationError
from app.utils.url_validator import validate_external_url

logger = logging.getLogger(__name__)


class StorageService:
    """Service for downloading and uploading files via presigned URLs.
    
    This service does not require any storage credentials. All uploads
    are performed via presigned URLs provided by the calling client.
    """

    def __init__(self, settings: Settings):
        """Initialize storage service.

        Args:
            settings: Application settings
        """
        self.settings = settings

    async def download_from_url(self, url: str) -> bytes:
        """Download remote content to memory.

        Args:
            url: Remote URL to fetch

        Returns:
            Content bytes

        Raises:
            ValidationError: If download fails or content is too large
        """
        logger.info(f"Downloading from URL: {url.split('?')[0]}")
        
        # Validate URL to prevent SSRF
        validate_external_url(url)
        
        try:
            async with httpx.AsyncClient(timeout=30.0) as client:
                # Manually handle redirects to validate each hop against SSRF rules
                current_url = url
                max_redirects = 5
                response = None

                for _ in range(max_redirects + 1):
                    response = await client.get(current_url, follow_redirects=False)

                    if response.is_redirect:
                        location = response.headers.get("Location")
                        if not location:
                            await response.aclose()
                            raise ValidationError("Redirect response missing Location header")

                        # Resolve relative URLs
                        next_url = str(httpx.URL(current_url).join(location))

                        # Validate the redirect target
                        validate_external_url(next_url)

                        current_url = next_url
                        await response.aclose()
                        continue

                    response.raise_for_status()
                    break
                else:
                    if response:
                        await response.aclose()
                    raise ValidationError(f"Too many redirects (max {max_redirects})")

                content = response.content
                settings = get_settings()

                if len(content) > settings.max_image_size_bytes:
                    from app.exceptions import FileTooLargeError
                    raise FileTooLargeError(
                        f"Downloaded content exceeds maximum size of {settings.max_image_size_mb}MB"
                    )

                return content
        except httpx.HTTPError as e:
            logger.error(f"Failed to download asset: {e}")
            raise ValidationError(f"Failed to download image from URL: {e}")

    async def upload_to_url(
        self,
        data: bytes,
        url: str,
        content_type: str = "application/octet-stream",
    ) -> str:
        """Upload data to a presigned URL.

        The presigned URL is generated by the calling client and includes
        all necessary authentication. This method simply performs a PUT
        request to the provided URL.

        Args:
            data: Data to upload
            url: Presigned destination URL
            content_type: MIME type of the content

        Returns:
            The URL uploaded to (without query parameters)

        Raises:
            UploadError: If upload fails after retries
        """
        # Validate URL to prevent SSRF
        validate_external_url(url)
        
        max_retries = 3

        for attempt in range(max_retries):
            try:
                async with httpx.AsyncClient(timeout=60.0) as client:
                    response = await client.put(
                        url,
                        content=data,
                        headers={"Content-Type": content_type},
                    )
                    response.raise_for_status()

                logger.info(
                    f"Uploaded to presigned URL",
                    extra={
                        "url_base": url.split("?")[0],
                        "size_bytes": len(data),
                        "content_type": content_type,
                    },
                )
                # Return URL without query params (the clean public URL)
                return url.split("?")[0]

            except httpx.HTTPError as e:
                logger.warning(
                    f"Upload attempt {attempt + 1} failed",
                    extra={"url": url.split("?")[0], "error": str(e)},
                )
                if attempt == max_retries - 1:
                    raise UploadError(f"Failed to upload after {max_retries} attempts: {e}")
                await asyncio.sleep(2**attempt)

        raise UploadError("Upload failed")
