"""Storage service for downloading and uploading via presigned URLs."""

import asyncio
import logging
from urllib.parse import urlparse

import httpx

from app.config import Settings, get_settings
from app.exceptions import UploadError, ValidationError
from app.utils.url_validator import validate_external_url

logger = logging.getLogger(__name__)


class StorageService:
    """Service for downloading and uploading files via presigned URLs.
    
    This service does not require any storage credentials. All uploads
    are performed via presigned URLs provided by the calling client.
    """

    _R2_HOST_SUFFIX = ".r2.cloudflarestorage.com"

    def __init__(self, settings: Settings):
        """Initialize storage service.

        Args:
            settings: Application settings
        """
        self.settings = settings

    async def download_from_url(self, url: str) -> bytes:
        """Download remote content to memory.

        Args:
            url: Remote URL to fetch

        Returns:
            Content bytes

        Raises:
            ValidationError: If download fails or content is too large
        """
        logger.info(f"Downloading from URL: {url.split('?')[0]}")
        
        # Validate URL to prevent SSRF
        validate_external_url(url)
        
        try:
            async with httpx.AsyncClient(timeout=30.0) as client:
                response = await client.get(url, follow_redirects=True)
                response.raise_for_status()

                content = response.content
                settings = get_settings()

                if len(content) > settings.max_image_size_bytes:
                    from app.exceptions import FileTooLargeError
                    raise FileTooLargeError(
                        f"Downloaded content exceeds maximum size of {settings.max_image_size_mb}MB"
                    )

                return content
        except httpx.HTTPError as e:
            logger.error(f"Failed to download asset: {e}")
            raise ValidationError(f"Failed to download image from URL: {e}")

    @staticmethod
    def _strip_query_params(url: str) -> str:
        """Remove query parameters from a URL."""
        return url.split("?", 1)[0]

    def resolve_public_url(self, upload_url: str) -> str:
        """Resolve a public playback URL from a presigned upload URL."""
        upload_url_base = self._strip_query_params(upload_url)
        parsed = urlparse(upload_url_base)

        if not parsed.scheme or not parsed.netloc:
            return upload_url_base

        if not parsed.netloc.endswith(self._R2_HOST_SUFFIX):
            return upload_url_base

        public_base = (self.settings.public_asset_base_url or "").strip()
        if not public_base:
            logger.warning(
                "PUBLIC_ASSET_BASE_URL not configured; falling back to upload URL for R2 object",
                extra={"upload_url_base": upload_url_base},
            )
            return upload_url_base

        object_key = parsed.path.lstrip("/")
        if not object_key:
            logger.warning(
                "Unable to resolve public URL from R2 upload URL with empty object key",
                extra={"upload_url_base": upload_url_base},
            )
            return upload_url_base

        return f"{public_base.rstrip('/')}/{object_key}"

    async def upload_to_url(
        self,
        data: bytes,
        url: str,
        content_type: str = "application/octet-stream",
    ) -> str:
        """Upload data to a presigned URL.

        The presigned URL is generated by the calling client and includes
        all necessary authentication. This method simply performs a PUT
        request to the provided URL.

        Args:
            data: Data to upload
            url: Presigned destination URL
            content_type: MIME type of the content

        Returns:
            Resolved public URL when available, otherwise the stripped upload URL

        Raises:
            UploadError: If upload fails after retries
        """
        # Validate URL to prevent SSRF
        validate_external_url(url)

        upload_url_base = self._strip_query_params(url)
        
        max_retries = 3

        for attempt in range(max_retries):
            try:
                async with httpx.AsyncClient(timeout=60.0) as client:
                    response = await client.put(
                        url,
                        content=data,
                        headers={"Content-Type": content_type},
                    )
                    response.raise_for_status()

                public_url = self.resolve_public_url(url)
                logger.info(
                    f"Uploaded to presigned URL",
                    extra={
                        "upload_url_base": upload_url_base,
                        "public_url": public_url,
                        "size_bytes": len(data),
                        "content_type": content_type,
                    },
                )
                return public_url

            except httpx.HTTPError as e:
                logger.warning(
                    f"Upload attempt {attempt + 1} failed",
                    extra={"upload_url_base": upload_url_base, "error": str(e)},
                )
                if attempt == max_retries - 1:
                    raise UploadError(f"Failed to upload after {max_retries} attempts: {e}")
                await asyncio.sleep(2**attempt)

        raise UploadError("Upload failed")
